import Head from "next/head";
import Header from "../components/header";
import Description from "../components/desc";
import Work from "../components/work";
import Test from "../components/footer";

const Home = () => {
  return (
    <>
      <Head>
        <title>CuddleZ - Home of the needy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Description />
      <Work />
      <Test />
    </>
  );
};

export default Home;
